# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903a046aa3a7f78d5e080e750493c8cb49a0cdd8cc360ca653a4c6b49ed2bfacf60b8802d23c14309fb262601eaef16197aac03e23f7020c29ed7e2767aaf364

test:
  secret_key_base: 084bdff6b6be757959bea6b1083a997dfe6e1ab6e9e8c7d1ac867818d7cc2547de2b2e22ffc88df763a4513008b553da3ab555420783dd83435e1c077ba918f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
